export enum ASSET_TYPES {
  COMPUTO = "Computo",
  OTROS = "Otros",
}

export enum REPORTS_TYPES {
  INFORME_CAUSACION_CTAS_COBRO = "INFORME_CAUSACION_CTAS_COBRO",
  INFORME_PAGO_CTAS_COBRO = "INFORME_PAGO_CTAS_COBRO",
  INFORME_CARTERA_VENCIDA = "INFORME_CARTERA_VENCIDA",
  INFORME_RADICACIÓN_GESTION_DOCUMENTAL = "INFORME_RADICACIÓN_GESTION_DOCUMENTAL",
}
